name: CI

on: [push, pull_request]

jobs:

  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Toolchain
        run: |
          cargo --version
          rustc --version

      - name: Check
        run: |
          cargo check

      - name: Build
        run: |
          cargo build --release

      - name: Test
        run: |
          cargo test --all

